spring:
  application:
    name: zuul
  rabbitmq:
    host: 192.168.17.130
    port: 5672
    username: admin
    password: admin
    
server:
  port: 3001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka

#默认的，可以不写
#zuul:
 # routes:
 #   item-service: /item-service/**
  #  user-service: /user-service/**
  #  order-service: /order-service/**
  
zuul:
  retryable: true
  
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
  
  